name: Deploy to AWS

on:
  push:
    branches:
      - main
      - dev
      - stg
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: portex-api-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Print environment variables
        run: |
            echo "SLS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}"
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set up Serverless Framework
        run: npm install -g serverless

      #- name: Configure Serverless Framework
      # run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Serverless Framework
        run: serverless login --token ${{ secrets.SERVERLESS_ACCESS_KEY }}         
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Serverless Framework
        run: npx serverless deploy --stage ${{ github.ref_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Rollback on failure
        if: failure()
        run: npx serverless rollback --stage ${{ github.ref_name }} --timestamp $(date +"%Y-%m-%dT%H:%M:%S")
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
